"""empty message

Revision ID: 28cd7addc610
Revises: 
Create Date: 2025-05-11 19:08:34.319159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28cd7addc610'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suhu', sa.Float(), nullable=True),
    sa.Column('kelembapan_udara', sa.Float(), nullable=True),
    sa.Column('kelembapan_tanah', sa.Float(), nullable=True),
    sa.Column('ketinggian_air', sa.Float(), nullable=True),
    sa.Column('dibuat_sejak', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hasil_prediksi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediksi_siram', sa.Boolean(), nullable=True),
    sa.Column('prediksi_kabut', sa.Boolean(), nullable=True),
    sa.Column('probabilitas_siram', sa.Float(), nullable=True),
    sa.Column('probabilitas_kabut', sa.Float(), nullable=True),
    sa.Column('dibuat_sejak', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jadwal_penyiraman',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('waktu_1', sa.Time(), nullable=True),
    sa.Column('waktu_2', sa.Time(), nullable=True),
    sa.Column('jenis_aksi', sa.Enum('penyiraman', 'pengkabutan', name='jenis_aksi_enum'), nullable=True),
    sa.Column('status', sa.Enum('aktif', 'nonaktif', name='status_enum'), nullable=True),
    sa.Column('dibuat_sejak', sa.DateTime(), nullable=True),
    sa.Column('diubah_sejak', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('riwayat_aksi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jenis_aksi', sa.Enum('penyiraman', 'pengkabutan', name='riwayat_aksi_enum'), nullable=True),
    sa.Column('status', sa.Enum('aktik', 'nonaktif', name='status_aksi_enum'), nullable=True),
    sa.Column('dibuat_sejak', sa.DateTime(), nullable=True),
    sa.Column('diubah_sejak', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('riwayat_aksi')
    op.drop_table('jadwal_penyiraman')
    op.drop_table('hasil_prediksi')
    op.drop_table('data_sensor')
    # ### end Alembic commands ###
