"""empty message

Revision ID: 8bf7b97709f4
Revises: 28cd7addc610
Create Date: 2025-05-11 19:09:02.503834

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8bf7b97709f4'
down_revision = '28cd7addc610'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riwayat_aksi', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('aktik', 'nonaktif'),
               type_=sa.Enum('aktif', 'nonaktif', name='status_aksi_enum'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riwayat_aksi', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('aktif', 'nonaktif', name='status_aksi_enum'),
               type_=mysql.ENUM('aktik', 'nonaktif'),
               existing_nullable=True)

    # ### end Alembic commands ###
